# Generated by Django 5.2.4 on 2025-07-10 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeler", "0002_alter_edge_id_alter_node_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                ("auto_save", models.BooleanField(default=True)),
                ("auto_save_interval", models.IntegerField(default=30)),
                ("snap_to_grid", models.BooleanField(default=True)),
                ("grid_size", models.IntegerField(default=16)),
                ("default_hub_prefix", models.CharField(default="HUB_", max_length=20)),
                (
                    "default_link_prefix",
                    models.CharField(default="LNK_", max_length=20),
                ),
                (
                    "default_satellite_prefix",
                    models.CharField(default="SAT_", max_length=20),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("json", "JSON"), ("sql", "SQL"), ("ddl", "DDL")],
                        default="json",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
    ]
