# Generated by Django 5.2.4 on 2025-07-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeler", "0003_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="auto_save_interval",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="default_hub_prefix",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="default_link_prefix",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="default_satellite_prefix",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="export_format",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="grid_size",
        ),
        migrations.AddField(
            model_name="settings",
            name="edge_animation",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="edge_type",
            field=models.CharField(
                choices=[
                    ("bezier", "Bezier"),
                    ("straight", "Straight"),
                    ("step", "Step"),
                    ("smoothstep", "Smooth Step"),
                ],
                default="smoothstep",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="floating_edges",
            field=models.BooleanField(default=True),
        ),
    ]
