# Generated by Django 5.2.4 on 2025-07-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeler", "0004_update_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="auto_save_interval",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="settings",
            name="grid_size",
            field=models.IntegerField(default=16),
        ),
    ]
