# Generated by Django 5.2.4 on 2025-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeler", "0005_add_back_canvas_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="show_connection_points",
            field=models.BooleanField(default=True),
        ),
    ]
