# Generated by Django 5.2.4 on 2025-07-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modeler", "0006_settings_show_connection_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="global_columns",
            field=models.JSONField(
                default=list, help_text="Global columns that appear in all node types"
            ),
        ),
    ]
